### ISSUE TITLE
Bug Report or README Update Suggestion For Absolute Paths

### ISSUE THREAD

**Issue by Pasqua101** [rook4715/tiller#1]
I was testing out conversion of a txt file I had the folder and provided the tiller program with the absolute path. Instead of typing it out, I decided to right click on the file and select the "copy as path" option. I started up the program as so `tiller "C:\Users\marco\Desktop\College\Year 3\OSD600\lab1\tiller\file1.txt"` and I was greeted with an error that showed `ENOENT: no such file or directory, open 'til/C:\Users\marco\Desktop\College\Year 3\OSD600\lab1\tiller\file1.html'`. However, if I were to edit the path so that instead of using **left slashes** it used **right slashes** like you would find in a **Linux absolute path** the program would run just fine. So my file path went from looking like `"C:\Users\marco\Desktop\College\Year 3\OSD600\lab1\tiller\file1.txt"` to  `"C:/Users/marco/Desktop/College/Year 3/OSD600/lab1/tiller/file1.txt"`. 

I suggest that you should try to update your program to support Window's absolute paths, or make it aware that the program does not support Window's absolute paths.

**Comment by rook4715** [comment]
Could you send the exact command you used?

![image](https://github.com/rook4715/tiller/assets/100863301/9bbf09cf-67bd-4f4e-ae33-94a893ce4548)

The tool is able to convert absolute paths on my end

**Comment by rook4715** [comment]
Never mind it occurs if you use a file as input
![image](https://github.com/rook4715/tiller/assets/100863301/977ad3d3-4e9d-4a1c-a89a-5f631844587e)

**Comment by rook4715** [comment]
![image](https://github.com/rook4715/tiller/assets/100863301/67e03c5d-1f06-40ec-bd73-a99bcb6ac2f2)
