### ISSUE TITLE
README Update

### ISSUE THREAD

**Issue by Pasqua101** [rook4715/tiller#3]
I suggest changing the first paragraph in your README to just say "tiller is a CLI tool that is able to convert txt files to .html files." instead of saying "tiller is a CLI tool that is able to convert input files to .html files. At the moment, only .txt files are supported.". If you'd like you could say that you're interested in expanding conversion support to other file formats.

**Comment by rook4715** [comment]
Next week involves adding support for markdown files, so conversion support will be expanded to .md files at the very least.
