### ISSUE TITLE
Markdown Support

### ISSUE THREAD

**Issue by Yousef-Majidi** [rook4715/tiller#6]
I would like to add markdown support to your project. 
Here is a list of changes I will make to your project:
- in `convert.js`:
   - add logic to detect `.md` files
   - modify the exception message accordingly
   - change the name of the function `convertFile` to `convertText`
   - introduce a new function called `convertMd` to contain the logic for markdown processing
   - add _`italics`_ support 
   - modify the `README` file to reflect the implemented changes

**Comment by rook4715** [comment]
Let me know if you have any questions about the program

**Comment by rook4715** [comment]
PR #7 has been merged
